version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=med_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Euphoria
      - POSTGRES_HOST=db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/medproject
    ports:
      - 8000:8000
    depends_on:
      - db