# Generated by Django 3.1.2 on 2021-01-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
