name: Med Appointment

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Euphoria
          POSTGRES_DB: med_db
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v1
      - name: Startup Services
        run: docker-compose -f docker-compose.yml up -d
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME: ${{ secrets.NAME }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          DEBUG: ${{ secrets.DEBUG }}
        run: python manage.py migrate
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME: ${{ secrets.NAME }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          DEBUG: ${{ secrets.DEBUG }}
        run: python manage.py test
      - name: Shutdown Services
        run: docker-compose down